(define
    (problem bw_1_from_epddl)
    (:domain blocks_world_from_epddl)

    (:agents
        robot - agent
    )

    (:objects
    )

    (:init
        (assign (clear_b1) 'f')
        (assign (clear_b2) 't')
        (assign (clear_b3) 't')
        (assign (clear_b4) 't')
        (assign (clear_c1) 'f')
        (assign (clear_c2) 'f')
        (assign (clear_c3) 'f')
        (assign (on_b1_b1) 'f')
        (assign (on_b1_b2) 'f')
        (assign (on_b1_b3) 'f')
        (assign (on_b1_b4) 'f')
        (assign (on_b1_c1) 't')
        (assign (on_b1_c2) 'f')
        (assign (on_b1_c3) 'f')
        (assign (on_b2_b1) 't')
        (assign (on_b2_b2) 'f')
        (assign (on_b2_b3) 'f')
        (assign (on_b2_b4) 'f')
        (assign (on_b2_c1) 'f')
        (assign (on_b2_c2) 'f')
        (assign (on_b2_c3) 'f')
        (assign (on_b3_b1) 'f')
        (assign (on_b3_b2) 'f')
        (assign (on_b3_b3) 'f')
        (assign (on_b3_b4) 'f')
        (assign (on_b3_c1) 'f')
        (assign (on_b3_c2) 't')
        (assign (on_b3_c3) 'f')
        (assign (on_b4_b1) 'f')
        (assign (on_b4_b2) 'f')
        (assign (on_b4_b3) 'f')
        (assign (on_b4_b4) 'f')
        (assign (on_b4_c1) 'f')
        (assign (on_b4_c2) 'f')
        (assign (on_b4_c3) 't')
    )

    (:goal (and
        (= (on_b4_b1) 't')
        (= (on_b3_b2) 't')
    ))

    (:ranges
        (clear_b1 enumerate ['t','f'])
        (clear_b2 enumerate ['t','f'])
        (clear_b3 enumerate ['t','f'])
        (clear_b4 enumerate ['t','f'])
        (clear_c1 enumerate ['t','f'])
        (clear_c2 enumerate ['t','f'])
        (clear_c3 enumerate ['t','f'])
        (on_b1_b1 enumerate ['t','f'])
        (on_b1_b2 enumerate ['t','f'])
        (on_b1_b3 enumerate ['t','f'])
        (on_b1_b4 enumerate ['t','f'])
        (on_b1_c1 enumerate ['t','f'])
        (on_b1_c2 enumerate ['t','f'])
        (on_b1_c3 enumerate ['t','f'])
        (on_b2_b1 enumerate ['t','f'])
        (on_b2_b2 enumerate ['t','f'])
        (on_b2_b3 enumerate ['t','f'])
        (on_b2_b4 enumerate ['t','f'])
        (on_b2_c1 enumerate ['t','f'])
        (on_b2_c2 enumerate ['t','f'])
        (on_b2_c3 enumerate ['t','f'])
        (on_b3_b1 enumerate ['t','f'])
        (on_b3_b2 enumerate ['t','f'])
        (on_b3_b3 enumerate ['t','f'])
        (on_b3_b4 enumerate ['t','f'])
        (on_b3_c1 enumerate ['t','f'])
        (on_b3_c2 enumerate ['t','f'])
        (on_b3_c3 enumerate ['t','f'])
        (on_b4_b1 enumerate ['t','f'])
        (on_b4_b2 enumerate ['t','f'])
        (on_b4_b3 enumerate ['t','f'])
        (on_b4_b4 enumerate ['t','f'])
        (on_b4_c1 enumerate ['t','f'])
        (on_b4_c2 enumerate ['t','f'])
        (on_b4_c3 enumerate ['t','f'])
    )

    (:rules
    )
)
